### ISSUE TITLE
"mouse-only" / "touch-only" devices

### ISSUE THREAD

**Issue by patrickhlauke** [rafrex/the-listener#1]
Just a point here that it's impossible in absolute terms to say a device is (always going to be) "mouse-only" or "touch-only". On a mobile ("touch-only") device, I can pair a bluetooth mouse. On a "mouse-only" device, I can attach an external touchscreen. In these scenarios, if I rely purely on the event listeners set at page load, I've made my page incompatible with the newly added/switched to input...and since the browsers currently don't seem to update things like CSS4 MQ interaction media feature results (e.g. Chrome on Android currently needs to be completely closed and reopened before it aknowledges that a fine/hover-capable device is present when a bluetooth mouse has been paired with the phone/tablet) or have any other notification mechanism that can be detected by JS, this may be quite an inconvenience for users. It may be worth pointing this out in the documentation / softening the "-only" descriptions.

**Comment by rafgraph** [comment]
@patrickhlauke I added a note to the readme about the edge case. Do you happen to have any stats on percent of sessions where the input types are change mid-session? 

In general, as much as I wish what I build could be optimized for every user, I find that developing for the web is a messy trade off providing the best experience for the majority of users at the expense of the minority of users - and finding the right balance based on percent of users and difference in experience is key.

**Comment by patrickhlauke** [comment]
no hard figures i can offer. the note seems appropriate though. thanks
